[settings]
animate = false
animation_duration = 0.3
animation_fps = 100.0
default_disable = false
focus_follows_mouse = false
mouse_follows_focus = false
mouse_hides_on_focus = false
auto_focus_blacklist = []
run_on_start = []
hot_reload = true

[settings.layout]
mode = "traditional"

[settings.layout.gaps.outer]
top = 0
bottom = 0
left = 0
right = 0

[settings.layout.gaps.inner]
horizontal = 0
vertical = 0

[settings.ui.menu_bar]
enabled = true
show_empty = false
display_style = "layout"

[settings.ui.mission_control]
enabled = true

[virtual_workspaces]
enabled = true
default_workspace_count = 10
default_workspace = 0
workspace_names = []
app_rules = [
    { app_id = "com.apple.calculator", floating = true },
    { app_id = "com.apple.ActivityMonitor", floating = true },
    { app_id = "com.apple.systempreferences", floating = true },
    { app_id = "com.apple.SystemSettings", floating = true },
    { app_name = "python", floating = true },
]

[modifier_combinations]
comb1 = "Alt + Shift"

[keys]
"Alt + Z" = "toggle_space_activated"

"Alt + H" = { move_focus = "left" }
"Alt + J" = { move_focus = "down" }
"Alt + K" = { move_focus = "up" }
"Alt + L" = { move_focus = "right" }

"comb1 + H" = { move_node = "left" }
"comb1 + J" = { move_node = "down" }
"comb1 + K" = { move_node = "up" }
"comb1 + L" = { move_node = "right" }

"Alt + 0" = { switch_to_workspace = 9 }
"Alt + 1" = { switch_to_workspace = 0 }
"Alt + 2" = { switch_to_workspace = 1 }
"Alt + 3" = { switch_to_workspace = 2 }
"Alt + 4" = { switch_to_workspace = 3 }
"Alt + 5" = { switch_to_workspace = 4 }
"Alt + 6" = { switch_to_workspace = 5 }
"Alt + 7" = { switch_to_workspace = 6 }
"Alt + 8" = { switch_to_workspace = 7 }
"Alt + 9" = { switch_to_workspace = 8 }

"comb1 + 0" = { move_window_to_workspace = 9 }
"comb1 + 1" = { move_window_to_workspace = 0 }
"comb1 + 2" = { move_window_to_workspace = 1 }
"comb1 + 3" = { move_window_to_workspace = 2 }
"comb1 + 4" = { move_window_to_workspace = 3 }
"comb1 + 5" = { move_window_to_workspace = 4 }
"comb1 + 6" = { move_window_to_workspace = 5 }
"comb1 + 7" = { move_window_to_workspace = 6 }
"comb1 + 8" = { move_window_to_workspace = 7 }
"comb1 + 9" = { move_window_to_workspace = 8 }

"Alt + Tab" = "switch_to_last_workspace"

"Alt + Ctrl + 1" = { set_workspace_layout = { mode = "traditional" } }
"Alt + Ctrl + 2" = { set_workspace_layout = { mode = "bsp" } }
"Alt + Ctrl + 3" = { set_workspace_layout = { mode = "master_stack" } }

"Alt + Shift + Left" = { join_window = "left" }
"Alt + Shift + Right" = { join_window = "right" }
"Alt + Shift + Up" = { join_window = "up" }
"Alt + Shift + Down" = { join_window = "down" }

"Alt + Comma" = "toggle_stack"
"Alt + Slash" = "toggle_orientation"
"Alt + Ctrl + E" = "unjoin_windows"

"Alt + Shift + Space" = "toggle_window_floating"
"Alt + F" = "toggle_fullscreen"

"Alt + Shift + Equal" = "resize_window_grow"
"Alt + Shift + Minus" = "resize_window_shrink"

"Alt + Ctrl + Up" = { move_window_to_display = { selector = "up" } }
"Alt + Ctrl + Down" = { move_window_to_display = { selector = "down" } }
"Alt + Ctrl + Left" = { move_window_to_display = { selector = "left" } }
"Alt + Ctrl + Right" = { move_window_to_display = { selector = "right" } }
"Alt + Ctrl + A" = { move_window_to_display = { selector = 0 } }

"Alt + Ctrl + Shift + M" = "show_mission_control_current"
"Alt + Ctrl + M" = "show_mission_control_all"

"Alt + Enter" = { "exec" = ["open", "-a", "ghostty"] }

"Alt + Shift + D" = "debug" # prints layout tree
"Alt + Ctrl + Q" = "save_and_exit"
